name: Clear pages cache

on:
  push:
    branches:
      - prod

jobs:
  wait:
    if: github.repository_owner == 'harbr-platform'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Cloudflare Pages deployment
        uses: WalshyDev/cf-pages-await@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: '598e2b99e180734d61cc299b4c5180c1'
          project: 'frontend-a6q'
          commitHash: ${{ steps.push-changes.outputs.commit-hash }}
      - name: Purge cache
        if: github.ref == 'refs/heads/prod'
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"hosts": ["harbr.nimq.com"]}' \
            https://api.cloudflare.com/client/v4/zones/bac9db702d6e52dfb380089659477bfe/purge_cache
